# Generated by Django 5.2.1 on 2026-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='L2Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direction', models.CharField(default='', max_length=5)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('size_multiplier', models.FloatField(default=0.0)),
                ('veto_reason', models.CharField(blank=True, max_length=50)),
                ('agents_summary', models.JSONField(default=dict)),
                ('trade_context', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='l2_agents_l_symbol_475ec1_idx')],
            },
        ),
    ]
