# Generated by Django 5.2.1 on 2026-04-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('l2_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2decision',
            name='dismissed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='l2decision',
            name='trade_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
