# Generated by Django 5.2.1 on 2026-04-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_change_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume_24h', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AggTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_buyer_maker', models.BooleanField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='ingester_ag_symbol_dd0fee_idx')],
            },
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('interval', models.CharField(db_index=True, max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('taker_buy_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('num_trades', models.IntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'interval', '-timestamp'], name='ingester_ca_symbol_d40a67_idx')],
                'unique_together': {('symbol', 'interval', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('funding_rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('mark_price', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('usd_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='ingester_li_symbol_c89299_idx')],
            },
        ),
        migrations.CreateModel(
            name='LongShortRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('long_account', models.DecimalField(decimal_places=4, max_digits=10)),
                ('short_account', models.DecimalField(decimal_places=4, max_digits=10)),
                ('long_short_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='OpenInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open_interest', models.DecimalField(decimal_places=8, max_digits=20)),
                ('open_interest_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='RetailCVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cumulative_delta', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='ingester_re_symbol_e739f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='TopTraderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('long_account', models.DecimalField(decimal_places=4, max_digits=10)),
                ('short_account', models.DecimalField(decimal_places=4, max_digits=10)),
                ('long_short_ratio', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='WhaleCVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('cumulative_delta', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='ingester_wh_symbol_e19f97_idx')],
            },
        ),
        migrations.CreateModel(
            name='WhaleThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('threshold_usd', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='ingester_wh_symbol_e0fd81_idx')],
            },
        ),
    ]
