# Generated by Django 5.2.1 on 2026-04-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
