# Generated by Django 5.2.1 on 2026-04-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('DAILY_STOP', 'Daily Stop Activated'), ('WEEKLY_STOP', 'Weekly Stop Activated'), ('LOSS_STREAK', 'Consecutive Loss Reduction'), ('VOLATILITY_SPIKE', 'Volatility Spike'), ('FUNDING_BLOCK', 'Funding Rate Block'), ('MAX_POSITIONS', 'Max Positions Reached'), ('POSITION_OPENED', 'Position Opened'), ('POSITION_CLOSED', 'Position Closed')], max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_pnl', models.FloatField(default=0)),
                ('weekly_pnl', models.FloatField(default=0)),
                ('consecutive_losses', models.IntegerField(default=0)),
                ('is_daily_stopped', models.BooleanField(default=False)),
                ('is_weekly_stopped', models.BooleanField(default=False)),
                ('position_size_multiplier', models.FloatField(default=1.0)),
                ('current_open_positions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Risk State',
                'verbose_name_plural': 'Risk State',
            },
        ),
    ]
