# Generated by Django 5.2.1 on 2026-04-28 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskstate',
            name='daily_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskstate',
            name='daily_start_equity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riskevent',
            name='event_type',
            field=models.CharField(choices=[('DAILY_STOP', 'Daily Stop Activated'), ('WEEKLY_STOP', 'Weekly Stop Activated'), ('LOSS_STREAK', 'Consecutive Loss Reduction'), ('VOLATILITY_SPIKE', 'Volatility Spike'), ('FUNDING_BLOCK', 'Funding Rate Block'), ('MAX_POSITIONS', 'Max Positions Reached'), ('POSITION_OPENED', 'Position Opened'), ('POSITION_CLOSED', 'Position Closed'), ('DAILY_PORTFOLIO_STOP', 'Daily Portfolio Stop')], max_length=20),
        ),
    ]
