# Generated by Django 5.2.1 on 2026-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystSignalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_name', models.CharField(db_index=True, max_length=30)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('score', models.FloatField()),
                ('bias', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['analyst_name', 'symbol', '-timestamp'], name='analysts_an_analyst_048d5c_idx')],
            },
        ),
    ]
