# Generated by Django 5.2.1 on 2026-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('direction', models.CharField(max_length=5)),
                ('strategy', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('entry_price', models.FloatField(null=True)),
                ('stop_loss', models.FloatField(null=True)),
                ('take_profit_1', models.FloatField(null=True)),
                ('take_profit_2', models.FloatField(null=True)),
                ('r_value', models.FloatField(null=True)),
                ('rr_planned', models.FloatField(null=True)),
                ('gates_a_passed', models.JSONField(default=dict)),
                ('gates_b_passed', models.JSONField(default=dict)),
                ('gates_c_passed', models.JSONField(default=dict)),
                ('regime', models.CharField(blank=True, max_length=20)),
                ('session', models.CharField(blank=True, max_length=10)),
                ('htf_bias', models.CharField(blank=True, max_length=10)),
                ('choppiness_index', models.FloatField(null=True)),
                ('l2_action', models.CharField(blank=True, max_length=10)),
                ('l2_size_multiplier', models.FloatField(default=1.0)),
                ('agent_verdicts', models.JSONField(default=dict)),
                ('veto_reason', models.CharField(blank=True, max_length=50)),
                ('executed', models.BooleanField(default=False)),
                ('shadow', models.BooleanField(default=False)),
                ('position_size_usd', models.FloatField(null=True)),
                ('state', models.CharField(choices=[('GENERATED', 'Generated'), ('APPROVED', 'L2 Approved'), ('REJECTED', 'L2 Rejected'), ('MONITORING', 'Monitoring'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], db_index=True, default='GENERATED', max_length=12)),
                ('closed_at', models.DateTimeField(null=True)),
                ('exit_price', models.FloatField(null=True)),
                ('exit_reason', models.CharField(blank=True, choices=[('SL', 'Stop Loss'), ('TP1', 'Take Profit 1'), ('TP2', 'Take Profit 2'), ('RUNNER_TRAIL', 'Runner Trailing'), ('TIME_KILL', 'Time Kill'), ('EOD', 'End of Day'), ('MANUAL', 'Manual Close'), ('EXPIRED', 'Signal Expired')], max_length=15)),
                ('outcome', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BREAKEVEN', 'Breakeven'), ('PARTIAL_WIN', 'Partial Win'), ('EXPIRED', 'Expired')], max_length=12)),
                ('pnl_r', models.FloatField(null=True)),
                ('pnl_usd', models.FloatField(null=True)),
                ('mfe_r', models.FloatField(null=True)),
                ('mae_r', models.FloatField(null=True)),
                ('time_in_trade_min', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'strategy', '-created_at'], name='evaluator_s_symbol_c0f529_idx'), models.Index(fields=['state', 'shadow'], name='evaluator_s_state_8fbdd2_idx')],
            },
        ),
    ]
