# Generated by Django 5.2.1 on 2026-04-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='L1Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short'), ('', 'Unknown')], default='', max_length=5)),
                ('passed', models.BooleanField(db_index=True)),
                ('gates_a', models.JSONField(default=dict)),
                ('gates_b', models.JSONField(default=dict)),
                ('gates_c', models.JSONField(default=dict)),
                ('gates_b_count', models.IntegerField(default=0)),
                ('gates_c_count', models.IntegerField(default=0)),
                ('trade_context', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='l1_filter_l_symbol_cca1d1_idx')],
            },
        ),
    ]
