# Generated by Django 5.2.1 on 2026-04-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField()),
                ('equity', models.FloatField()),
                ('unrealized_pnl', models.FloatField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_pnl', models.FloatField(default=0)),
                ('max_drawdown', models.FloatField(default=0)),
                ('peak_equity', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(max_length=5)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('position_size_usd', models.FloatField()),
                ('pnl', models.FloatField()),
                ('pnl_percent', models.FloatField()),
                ('risk_reward', models.FloatField(default=0)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('close_reason', models.CharField(blank=True, max_length=50)),
                ('analyst_snapshot', models.JSONField(blank=True, default=dict)),
                ('conviction_score', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-exit_time'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('entry_price', models.FloatField()),
                ('current_price', models.FloatField(default=0)),
                ('quantity', models.FloatField()),
                ('position_size_usd', models.FloatField()),
                ('leverage', models.IntegerField(default=1)),
                ('stop_loss', models.FloatField()),
                ('take_profit_1', models.FloatField(null=True)),
                ('take_profit_2', models.FloatField(null=True)),
                ('take_profit_3', models.FloatField(null=True)),
                ('tp1_hit', models.BooleanField(default=False)),
                ('tp2_hit', models.BooleanField(default=False)),
                ('tp3_hit', models.BooleanField(default=False)),
                ('sl_moved_to_be', models.BooleanField(default=False)),
                ('chandelier_stop', models.FloatField(blank=True, null=True)),
                ('strategy', models.CharField(default='S1', max_length=5)),
                ('remaining_quantity', models.FloatField(default=0)),
                ('realized_pnl', models.FloatField(default=0)),
                ('unrealized_pnl', models.FloatField(default=0)),
                ('consensus_signal_id', models.IntegerField(null=True)),
                ('tier', models.CharField(blank=True, max_length=20)),
                ('analyst_snapshot', models.JSONField(blank=True, default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['status', 'symbol'], name='executor_po_status_95b8d3_idx')],
            },
        ),
    ]
