# Generated by Django 5.2.1 on 2026-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='liquidation_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='margin_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='source',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
