# Generated by Django 5.2.1 on 2026-04-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0002_position_liquidation_price_position_margin_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(max_length=5)),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('pnl_usd', models.FloatField()),
                ('close_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_event', to='executor.trade')),
            ],
            options={
                'ordering': ['-close_date'],
            },
        ),
    ]
