# Generated by Django 5.2.1 on 2026-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0003_taxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstate',
            name='spot_reserve_balance',
            field=models.FloatField(default=0),
        ),
    ]
