# Generated by Django 5.2.1 on 2026-04-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executor', '0004_accountstate_spot_reserve_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOpenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('client_oid', models.CharField(blank=True, default='', max_length=100)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=5)),
                ('order_type', models.CharField(blank=True, default='', max_length=20)),
                ('price', models.FloatField(default=0)),
                ('size', models.FloatField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('source', models.CharField(default='exchange', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol', 'order_id'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='executor_ex_symbol_6cadb3_idx')],
            },
        ),
    ]
