# Generated by Django 5.2.1 on 2026-04-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('strategy', models.CharField(max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.FloatField(default=10000.0)),
                ('risk_per_trade', models.FloatField(default=0.005)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('sharpe_ratio', models.FloatField(default=0)),
                ('calmar_ratio', models.FloatField(default=0)),
                ('max_drawdown', models.FloatField(default=0)),
                ('total_pnl', models.FloatField(default=0)),
                ('total_pnl_pct', models.FloatField(default=0)),
                ('final_capital', models.FloatField(default=0)),
                ('mc_ruin_probability', models.FloatField(null=True)),
                ('mc_worst_5pct_dd', models.FloatField(null=True)),
                ('mc_median_sharpe', models.FloatField(null=True)),
                ('equity_curve', models.JSONField(blank=True, default=list)),
                ('trades_detail', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
