# Generated by Django 5.2.1 on 2026-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conviction_score', models.FloatField()),
                ('bias', models.CharField(max_length=10)),
                ('tier', models.CharField(choices=[('NONE', 'No Signal'), ('WATCH', 'Watch'), ('SIGNAL', 'Signal'), ('HIGH_CONVICTION', 'High Conviction')], default='NONE', max_length=20)),
                ('agreeing_analysts', models.IntegerField(default=0)),
                ('total_analysts', models.IntegerField(default=6)),
                ('momentum_score', models.FloatField(default=0)),
                ('volume_flow_score', models.FloatField(default=0)),
                ('structure_score', models.FloatField(default=0)),
                ('sentiment_score', models.FloatField(default=0)),
                ('llm_narrative_score', models.FloatField(default=0)),
                ('cross_asset_score', models.FloatField(default=0)),
                ('analyst_details', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='consensus_c_symbol_66d2a7_idx')],
            },
        ),
    ]
